name: deploy

on: [ push ]

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
        
      - name: Setup Node.js environment
        uses: actions/setup-node@latest

      - name: Run a one-line script
        run: npm run build
