name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm run build

      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'gh-pages'
          commit_message: 'deploy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
